<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;


use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Financeiro\Bancos;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class BancosNiSelect2Type extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {


        return $builder
            ->add('ni',ChoiceType::class,[
                'label'=>false,
                'required'=>true,
                'attr'=>[
                    'class'=>'select2',
                    'required'=>'required'
                ],
                'choices'=>$this->obterBancos()
            ]);
    }


    public function getBlockPrefix()
    {
        return false;
    }

    public function configureOptions(OptionsResolver $resolver)
    {

        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }


    private function obterBancos(){

        $bancos = $this->getDoctrine()->getRepository(Bancos::class)
            ->findAll();

        $params = [];

        /**
         * @var Bancos $banco
        */

        foreach($bancos as $banco) {
            $params[$banco->getNome()] = $banco->getNiBanco()->getNi();
        }


        return $params;

    }

}