<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;

use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Financeiro\Bancos;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class BancoChoicesType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        return $builder
            ->add('niBanco',ChoiceType::class,[
                'label'=>'Bancos',
                'required'=>true,
                'multiple'=>'multiple',
                'attr'=>[
                    'class'=>'select2',
                ],
                'choices'=>$this->obterbancos()
            ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=>Bancos::class
        ]);

        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    private function obterbancos(){


        $bancos = $this->getDoctrine()->getRepository(Bancos::class)->findAll();

        $dados = [];
        foreach ($bancos as $banco){
            $dados[$banco->getNome()] = $banco->getNiBanco()->getNi();
        }

        return $dados;

    }

}