<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;



use Helpers\FormType\Choices\EstadoCivil;
use Helpers\FormType\Choices\Nacionalidade;
use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Central\PessoaFisica;
use Rtd\Suporte\Entity\Financeiro\Bancos;
use Rtd\Suporte\Entity\Financeiro\BancosCentral;
use Rtd\Suporte\Entity\Financeiro\CanaisDeVenda;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class CanaisDeVendaType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        return $builder
            ->add('ni',PessoaNiSelect2Type::class,[
                'label'=>'Selecione um Cliente'
            ])
            ->add('identificador',TextType::class,[
                'label'=>'Identificador',
                'label_attr'=>[
                    'class'=>'text-danger'
                ]
            ])
            ->add('dataAdesao',DateType::class,[
                'widget'=>'single_text',
               'label'=>'Data de Adesão',
                'placeholder'=>'dia/mes/ano',
                'html5'=>true
            ])
            ->add('ativo',CheckboxType::class,[
               'label'=>'Este canal está ativo?',
               'required'=>false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=>CanaisDeVenda::class,
            'attr'=>[
                'class'=>'bg-info'
            ]
        ]);
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

}