<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;



use Helpers\FormType\Choices\EstadoCivil;
use Helpers\FormType\Choices\Nacionalidade;
use Helpers\FormType\Choices\Pais;
use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Central\PessoaFisica;
use Rtd\Suporte\Entity\Financeiro\Bancos;
use Rtd\Suporte\Entity\Financeiro\ClientesFaturados;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class ClientesFaturadosType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        return $builder
            ->add('ni',PessoaNiSelect2Type::class,[
                'label'=>'Pessoa',
                'required'=>true,
                'attr'=>[
                    'required'=>'required'
                ]
            ])
            ->add('dataAdesao',DateType::class,[
                'widget'=>'single_text'
            ])
            ->add('periodicidadeFatura',IntegerType::class,[
                'required'=>false,
                'attr'=>[
                    'min'=>1,
                    'max'=>365,
                    'required'=>false
                ]
            ])
            ->add('diaFechamentoFatura',IntegerType::class,[
                'required'=>false,
                'attr'=>[
                    'min'=>1,
                    'max'=>28,
                    'required'=>false
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=>ClientesFaturados::class
        ]);
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

}