<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;





use Helpers\FormType\Choices\TiposComplementos;
use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Central\Complementos;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class ComplementoType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        return $builder
            ->add('id',HiddenType::class)
            ->add('tipo',ChoiceType::class,(new TiposComplementos())->make())
            ->add('identificacao',TextType::class,[
               'label'=>'Descrição do complemento',
                'attr'=>[
                    'maxlength'=>100,
                ]
            ])
            ->add('idEndereco',EnderecoIdType::class,[
                "label"=>false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=> Complementos::class
        ]);

        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

}