<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;


use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Central\Estados;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class EstadoType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {



        return $builder
            ->add('estadoId',ChoiceType::class,[
                'label'=>'Estados',
                'choices'=>$this->carregaEstados(),
                'attr'=>[
                    'class'=>'estado-select-2',
                ]
            ]);
    }


    public function configureOptions(OptionsResolver $resolver)
    {

        $resolver->setDefaults([
            'data_class'=>Estados::class,
            'attr'=>[
                'required'=>true
            ]

        ]);

        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    private function carregaEstados(){

        $estados = $this->getDoctrine()->getRepository(Estados::class)->findAll();

        $estadosColections = [];

        /**
         * @var Estados $estado
         */
        foreach($estados as $estado){

            $estadosColections[$estado->getDescEstado()] = $estado->getEstadoId();
        }

        return $estadosColections;

    }


}