<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;


use Helpers\Formulario\FormType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class PessoaType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        return $builder
            ->add('ni',TextType::class,[
                'label'=>'Cpf Cnpj',
                'attr'=>[
                    'class'=>'cpfcnpj'
                ]
            ])
            ->add('nome',TextType::class,[
                'attr'=>[
                    'maxlength'=>120,
                ]
            ])
            ->add('nomeUsual',TextType::class,[
                'required'=>false,
                'attr'=>[
                    'maxlength'=>200,
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {

        $resolver->setDefaults([
            'data_class'=>\Rtd\Suporte\Entity\Central\Pessoa::class,
        ]);

        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }


}