<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;



use Helpers\FormType\Choices\EstadoCivil;
use Helpers\FormType\Choices\Nacionalidade;
use Helpers\FormType\Choices\Pais;
use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Central\PessoaFisica;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class PessoaFisicaType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        return $builder
            ->add('ni',ChoiceType::class,[
                'label'=>'Pessoa',
                'required'=>true,
                'attr'=>[
                    'class'=>'select2-ajax-pessoa',
                    'required'=>'required'
                ],
            ])
            ->add('dataNascimento',DateType::class,[
            'widget'=>'single_text',
            'format'=>'yyyy-MM-dd'
            ])
            ->add('estadoCivil',ChoiceType::class,(new EstadoCivil())->make())
            ->add('uniaoEstavel',CheckboxType::class,[
                'required'=>false,
                'attr'=>[
                    'maxlength'=>100,
                ]
            ])
            ->add('nacionalidade',ChoiceType::class,(new Nacionalidade())->make())
            ->add('pais',ChoiceType::class,(new Pais())->make())
            ->add('profissao',TextType::class,[
                'attr'=>[
                    'maxlength'=>200,
                ]
            ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {

        $resolver->setDefaults([
            'data_class'=>PessoaFisica::class
        ]);
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

}