<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;


use Helpers\Formulario\FormType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class PessoaNiSelect2Type extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        return $builder
            ->add('ni',ChoiceType::class,[
                'label'=>false,
                'required'=>true,
                'attr'=>[
                    'class'=>'select2-ajax-pessoa',
                    'required'=>'required'
                ],
            ]);
    }


    public function getBlockPrefix()
    {
        return false;
    }

    public function configureOptions(OptionsResolver $resolver)
    {

        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }


}