<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;


use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Central\Servico;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class ServicoType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        return $builder
            ->add('idServico',HiddenType::class)
            ->add('descricao', TextType::class, [
                'label' => 'Nome do Serviço',
                'attr'=>[
                    'maxlength'=>100,
                ]
            ])
            ->add('sigla', TextType::class,[
                'attr'=>[
                    'maxlength'=>2,
                    'minlength'=>2
                ]
            ])
            ->add('tabelaDados', TextType::class,[
                'attr'=>[
                    'maxlength'=>50,
                ]
            ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=>Servico::class
        ]);

        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }


}