<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;

use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Financeiro\Bancos;
use Rtd\Suporte\Entity\Financeiro\TarifasBancarias;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class TarifasBancariasChoicesType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        return $builder
            ->add('id',ChoiceType::class,[
                'label'=>'Tarifas bancárias',
                'required'=>true,
                'attr'=>[
                    'class'=>'select2',
                ],
                'choices'=>$this->obterTarifas()
            ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=>TarifasBancarias::class
        ]);

        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    private function obterTarifas(){

        $tarifas = $this->getDoctrine()->getRepository(TarifasBancarias::class)->findAll();

        $dados = [];
        foreach ($tarifas as $tarifa){
            $dados[$tarifa->getDescricao()] = $tarifa->getId();
        }

        return $dados;

    }

}