<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;


use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Financeiro\TaxasConveniencia;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class TaxaConvenienciaType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        return $builder
            ->add('id',HiddenType::class)
            ->add('descricao', TextType::class, [
                'label' => 'Descrição da taxa',
                'attr'=>[
                    'maxlength'=>100,
                ]
            ])
            ->add('percentual', CheckboxType::class,[
                'label'=>'A taxa é percentual?',
                'required'=>false
            ]);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=>TaxasConveniencia::class
        ]);

        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }


}