<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;



use Helpers\FormType\Choices\EstadoCivil;
use Helpers\FormType\Choices\Nacionalidade;
use Helpers\FormType\Choices\Pais;
use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Central\PessoaFisica;
use Rtd\Suporte\Entity\Financeiro\Bancos;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class UpdateBancoType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        return $builder
            ->add('niBanco',PessoaNiType::class,[
                'label'=>false,
                'auto_initialize'=>true,
                'compound'=> true
            ])
            ->add('codigo',TextType::class,[
               'label'=>'Código da Instituição bancária'
            ])
            ->add('nome',TextType::class,[
                'label'=>'Nome da instituição bancária',
                'attr'=>[
                    'maxlength'=>50
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=>Bancos::class,
        ]);
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

}