<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;


use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Central\Pessoa;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class UpdatePessoaType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        return $builder
            ->add('ni',HiddenType::class,[
                'label'=>'Cpf Cnpj',

            ])
            ->add('nome',TextType::class)
            ->add('nomeUsual',TextType::class,[
                'required'=>false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
           'data_class'=>Pessoa::class
        ]);
        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }


}