<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 31/08/18
 * Time: 17:35
 */

namespace Rtd\Suporte\Service\Form;




use Helpers\Formulario\FormType;
use Rtd\Suporte\Entity\Central\FormaContato;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class UpdateFormaContatoType extends FormType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        return $builder
            ->add('ni',PessoaNiType::class,[
                'label'=>false
            ])
            ->add('id',HiddenType::class)
            ->add('tipo',ChoiceType::class,[
                'label'=>'Tipo de Contato',
                'choices'=>[
                    'e-Mail'=>'e-Mail',
                    'Celular'=>'Celular',
                    'Telefone'=>'Telefone',
                    'Fax'=>'Fax'
                ],
                ])
            ->add('identificador',TextType::class,[
               'label'=>'Identificador do contato'
            ]);
        
    }

    public function configureOptions(OptionsResolver $resolver)
    {

        parent::configureOptions($resolver); // TODO: Change the autogenerated stub

        $resolver->setDefaults([
            'data_class'=>FormaContato::class
        ]);
    }

}