<?php
/**
 * Created by PhpStorm.
 * User: jonantah
 * Date: 06/11/18
 * Time: 11:48
 */

namespace Helpers\Constantes;

class StatusServico
{

    const AGUARDANDO_ASSINATURAS = 1,
        AGUARDANDO_SER_DISTRIBUIDO = 2,
        AGURDANDO_INFORMAR_CUSTAS = 3,
        CARTORIO_COM_PENDENCIA_TECNOLOGICA = 4,
        AGURDANDO_EXIGENCIAS = 5,
        AGURDANDO_ANALISE_RESPOSTA_NOTA_DEVOLUTIVA = 6,
        AGUARDANDO_FINALIZAR_PEDIDO = 7,
        AGUARDANDO_CONFIRMAR_PAGAMENTO = 8,
        AGUARDANDO_REGISTRO = 9,
        AGUARDANDO_RESULTADO_BUSCA = 10,
        AGUARDANDO_RESULTADO_PEDIDO_CERTIDAO = 11,
        CANCELAMENTO_SOLICITADO = 12,
        DOCUMENTO_CANCELADO = 13,
        REGISTRADO = 14,
        REGISTRADO_AGUARDANDO_RETORNO = 15,
        CONCLUIDO = 15,
        CONCLUIDO_NEGATIVO = 17,
        CONCLUIDO_POSITIVO = 18,
        DOCUMENTO_ASSINADO = 19,
        CONCLUIDO_POSITIVO_ENTREGUE_POR_HORA_CERTA = 20,
        CONCLUIDO_POSITIVO_ENTREGUE_PRESENCIALMENTE = 21,
        CONCLUIDO_NEGATIVO_NOTIFICADO_SE_OCULTOU = 22,
        CONCLUIDO_NEGATIVO_ENDERECO_NOTIFICADO_DESCONHECIDO_INCERTO_OU_INACESSIVEL = 23,
        CONCLUIDO_NEGATIVO_IMPOSSIBILITADO_TEMPORARIAMENTE_DE_SER_NOTIFICADO = 24;

}

